name: cabo
description: A board to track cabo game stats

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  flutter_circular_text: ^0.3.1
  flutter_bloc: ^8.0.0
  url_launcher: ^6.0.14
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.1.1
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.0.0
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/CABO-1024x1024.png"
  min_sdk_android: 21

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Aclonica
      fonts:
        - asset: fonts/Aclonica-Regular.ttf

