name: cabo
description: A board to track cabo game stats

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.3+14

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  flutter_circular_text: ^0.3.1
  flutter_bloc: ^8.0.0
  url_launcher: ^6.0.14
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.1.1
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0
  http: ^1.2.0
  logging: 1.2.0
  simple_gradient_text: ^1.3.0
  in_app_review: ^2.0.10
  confetti: ^0.8.0
  flutter_native_splash: ^2.4.4
  mobile_scanner: ^6.0.10
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.11
  pretty_qr_code: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.0.0
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.11.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/cabo-logo-512.png"
  min_sdk_android: 24
  adaptive_icon_foreground: "assets/icon/cabo-logo-512.png"
  adaptive_icon_background: "#5EEEB2"
  adaptive_icon_foreground_inset: 0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Aclonica
      fonts:
        - asset: fonts/Aclonica-Regular.ttf
    - family: Archivo
      fonts:
        - asset: fonts/Archivo-Bold.ttf
          weight: 700
        - asset: fonts/Archivo-Light.ttf
          weight: 300
        - asset: fonts/Archivo-Medium.ttf
          weight: 500
        - asset: fonts/Archivo-Regular.ttf
          weight: 400

