// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnW-tIdYtYfDqAMnvR855pKlv3l3qfyw',
    appId: '1:787934087365:android:35b8efdbe106dc6800c8ac',
    messagingSenderId: '787934087365',
    projectId: 'cabo-9be98',
    databaseURL: 'https://cabo-9be98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cabo-9be98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChC34dWaJlhOLDtC4jxsmqIB9K2__UIn8',
    appId: '1:787934087365:ios:fe48875372e1c1fe00c8ac',
    messagingSenderId: '787934087365',
    projectId: 'cabo-9be98',
    databaseURL: 'https://cabo-9be98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cabo-9be98.firebasestorage.app',
    androidClientId: '787934087365-eong57bv1h7q611iotli2bvvlpfvjslp.apps.googleusercontent.com',
    iosClientId: '787934087365-o3pood9aonln9jkij0fs9puq76fukinu.apps.googleusercontent.com',
    iosBundleId: 'com.buggxs.cabo',
  );
}
