// Mocks generated by Mockito 5.4.6 from annotations
// in cabo/test/components/application/cubit/application_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cabo/domain/announcement/announcement_check_service.dart'
    as _i12;
import 'package:cabo/domain/announcement/announcement_repository.dart' as _i4;
import 'package:cabo/domain/announcement/local_announcement_repository.dart'
    as _i5;
import 'package:cabo/domain/application/auth_service.dart' as _i3;
import 'package:cabo/domain/application/deep_link_service.dart' as _i8;
import 'package:cabo/domain/application/local_application_repository.dart'
    as _i9;
import 'package:cabo/domain/application/local_design_repository.dart' as _i11;
import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthOutcome_1 extends _i1.SmartFake implements _i3.AuthOutcome {
  _FakeAuthOutcome_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnnouncementRepository_2 extends _i1.SmartFake
    implements _i4.AnnouncementRepository {
  _FakeAnnouncementRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalAnnouncementRepository_3 extends _i1.SmartFake
    implements _i5.LocalAnnouncementRepository {
  _FakeLocalAnnouncementRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_4 extends _i1.SmartFake implements _i6.UserMetadata {
  _FakeUserMetadata_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_5 extends _i1.SmartFake implements _i6.MultiFactor {
  _FakeMultiFactor_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_6 extends _i1.SmartFake implements _i6.IdTokenResult {
  _FakeIdTokenResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_7 extends _i1.SmartFake
    implements _i6.UserCredential {
  _FakeUserCredential_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_8 extends _i1.SmartFake
    implements _i6.ConfirmationResult {
  _FakeConfirmationResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_9 extends _i1.SmartFake implements _i6.User {
  _FakeUser_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
            returnValueForMissingStub: _FakeLogger_0(
              this,
              Invocation.getter(#logger),
            ),
          )
          as _i2.Logger);

  @override
  _i7.Stream<_i6.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i7.Stream<_i6.User?>.empty(),
            returnValueForMissingStub: _i7.Stream<_i6.User?>.empty(),
          )
          as _i7.Stream<_i6.User?>);

  @override
  _i7.Future<void> initializeProviders() =>
      (super.noSuchMethod(
            Invocation.method(#initializeProviders, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.AuthOutcome> ensureSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#ensureSignedIn, []),
            returnValue: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(this, Invocation.method(#ensureSignedIn, [])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(this, Invocation.method(#ensureSignedIn, [])),
            ),
          )
          as _i7.Future<_i3.AuthOutcome>);

  @override
  _i7.Future<_i3.AuthOutcome> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i7.Future<_i3.AuthOutcome>);

  @override
  _i7.Future<_i3.AuthOutcome> registerWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#registerWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#registerWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.AuthOutcome>);

  @override
  _i7.Future<_i3.AuthOutcome> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#signInWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#signInWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.AuthOutcome>);

  @override
  _i7.Future<_i3.AuthOutcome> sendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#sendVerificationEmail, []),
            returnValue: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#sendVerificationEmail, []),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#sendVerificationEmail, []),
              ),
            ),
          )
          as _i7.Future<_i3.AuthOutcome>);

  @override
  _i7.Future<bool> refreshVerificationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#refreshVerificationStatus, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i3.AuthOutcome> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
          )
          as _i7.Future<_i3.AuthOutcome>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.AuthOutcome> linkOrSignInForTest(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkOrSignInForTest, [credential]),
            returnValue: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#linkOrSignInForTest, [credential]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AuthOutcome>.value(
              _FakeAuthOutcome_1(
                this,
                Invocation.method(#linkOrSignInForTest, [credential]),
              ),
            ),
          )
          as _i7.Future<_i3.AuthOutcome>);
}

/// A class which mocks [DeepLinkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkService extends _i1.Mock implements _i8.DeepLinkService {
  @override
  _i7.Stream<Uri> get linkStream =>
      (super.noSuchMethod(
            Invocation.getter(#linkStream),
            returnValue: _i7.Stream<Uri>.empty(),
            returnValueForMissingStub: _i7.Stream<Uri>.empty(),
          )
          as _i7.Stream<Uri>);

  @override
  _i7.Future<Uri?> getInitialLink() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialLink, []),
            returnValue: _i7.Future<Uri?>.value(),
            returnValueForMissingStub: _i7.Future<Uri?>.value(),
          )
          as _i7.Future<Uri?>);

  @override
  bool isEmailVerifiedLink(Uri? uri) =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerifiedLink, [uri]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [LocalApplicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalApplicationRepository extends _i1.Mock
    implements _i9.LocalApplicationRepository {
  @override
  String get storageKey =>
      (super.noSuchMethod(
            Invocation.getter(#storageKey),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#storageKey),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#storageKey),
            ),
          )
          as String);

  @override
  bool castMapToObject(dynamic object) =>
      (super.noSuchMethod(
            Invocation.method(#castMapToObject, [object]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<List<bool>?> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i7.Future<List<bool>?>.value(),
            returnValueForMissingStub: _i7.Future<List<bool>?>.value(),
          )
          as _i7.Future<List<bool>?>);

  @override
  _i7.Future<void> saveAll(List<bool>? objectList) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [objectList]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool?> saveCurrent(bool? object) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrent, [object]),
            returnValue: _i7.Future<bool?>.value(),
            returnValueForMissingStub: _i7.Future<bool?>.value(),
          )
          as _i7.Future<bool?>);

  @override
  _i7.Future<bool?> getCurrent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrent, []),
            returnValue: _i7.Future<bool?>.value(),
            returnValueForMissingStub: _i7.Future<bool?>.value(),
          )
          as _i7.Future<bool?>);
}

/// A class which mocks [LocalDesignRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDesignRepository extends _i1.Mock
    implements _i11.LocalDesignRepository {
  @override
  String get storageKey =>
      (super.noSuchMethod(
            Invocation.getter(#storageKey),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#storageKey),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#storageKey),
            ),
          )
          as String);

  @override
  String castMapToObject(dynamic object) =>
      (super.noSuchMethod(
            Invocation.method(#castMapToObject, [object]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#castMapToObject, [object]),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.method(#castMapToObject, [object]),
            ),
          )
          as String);

  @override
  _i7.Future<List<String>?> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i7.Future<List<String>?>.value(),
            returnValueForMissingStub: _i7.Future<List<String>?>.value(),
          )
          as _i7.Future<List<String>?>);

  @override
  _i7.Future<void> saveAll(List<String>? objectList) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [objectList]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> saveCurrent(String? object) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrent, [object]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> getCurrent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrent, []),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);
}

/// A class which mocks [AnnouncementCheckService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnnouncementCheckService extends _i1.Mock
    implements _i12.AnnouncementCheckService {
  @override
  _i4.AnnouncementRepository get announcementRepository =>
      (super.noSuchMethod(
            Invocation.getter(#announcementRepository),
            returnValue: _FakeAnnouncementRepository_2(
              this,
              Invocation.getter(#announcementRepository),
            ),
            returnValueForMissingStub: _FakeAnnouncementRepository_2(
              this,
              Invocation.getter(#announcementRepository),
            ),
          )
          as _i4.AnnouncementRepository);

  @override
  _i5.LocalAnnouncementRepository get localAnnouncementRepository =>
      (super.noSuchMethod(
            Invocation.getter(#localAnnouncementRepository),
            returnValue: _FakeLocalAnnouncementRepository_3(
              this,
              Invocation.getter(#localAnnouncementRepository),
            ),
            returnValueForMissingStub: _FakeLocalAnnouncementRepository_3(
              this,
              Invocation.getter(#localAnnouncementRepository),
            ),
          )
          as _i5.LocalAnnouncementRepository);

  @override
  _i7.Future<void> checkAndShowAnnouncement() =>
      (super.noSuchMethod(
            Invocation.method(#checkAndShowAnnouncement, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> forceShowAnnouncement() =>
      (super.noSuchMethod(
            Invocation.method(#forceShowAnnouncement, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i6.User {
  @override
  bool get emailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_4(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeUserMetadata_4(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i6.UserMetadata);

  @override
  List<_i6.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i6.UserInfo>[],
            returnValueForMissingStub: <_i6.UserInfo>[],
          )
          as List<_i6.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i10.dummyValue<String>(this, Invocation.getter(#uid)),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#uid),
            ),
          )
          as String);

  @override
  _i6.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_5(
              this,
              Invocation.getter(#multiFactor),
            ),
            returnValueForMissingStub: _FakeMultiFactor_5(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i6.MultiFactor);

  @override
  _i7.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i6.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i7.Future<_i6.IdTokenResult>.value(
              _FakeIdTokenResult_6(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.IdTokenResult>.value(
              _FakeIdTokenResult_6(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i7.Future<_i6.IdTokenResult>);

  @override
  _i7.Future<_i6.UserCredential> linkWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i6.UserCredential>);

  @override
  _i7.Future<_i6.UserCredential> linkWithProvider(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i7.Future<_i6.UserCredential>);

  @override
  _i7.Future<_i6.UserCredential> reauthenticateWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i7.Future<_i6.UserCredential>);

  @override
  _i7.Future<_i6.UserCredential> reauthenticateWithPopup(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i7.Future<_i6.UserCredential>);

  @override
  _i7.Future<void> reauthenticateWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.UserCredential> linkWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i7.Future<_i6.UserCredential>);

  @override
  _i7.Future<void> linkWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i6.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i7.Future<_i6.ConfirmationResult>.value(
              _FakeConfirmationResult_8(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.ConfirmationResult>.value(
              _FakeConfirmationResult_8(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i7.Future<_i6.ConfirmationResult>);

  @override
  _i7.Future<_i6.UserCredential> reauthenticateWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i6.UserCredential>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendEmailVerification([
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i7.Future<_i6.User>.value(
              _FakeUser_9(this, Invocation.method(#unlink, [providerId])),
            ),
            returnValueForMissingStub: _i7.Future<_i6.User>.value(
              _FakeUser_9(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i7.Future<_i6.User>);

  @override
  _i7.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhoneNumber(
    _i6.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
